language: generic

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8

after_success:
  - mv rtld-aarch64.nso rtld-aarch64-$TRAVIS_TAG.nso
  - mv rtld-aarch64-6xx.nso rtld-aarch64-6xx-$TRAVIS_TAG.nso
  - mv rtld-armv7.nso rtld-armv7-$TRAVIS_TAG.nso
  - mv rtld-armv7-6xx.nso rtld-armv7-6xx-$TRAVIS_TAG.nso

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "rtld-aarch64-$TRAVIS_TAG.nso"
      - "rtld-aarch64-6xx-$TRAVIS_TAG.nso"
      - "rtld-armv7-$TRAVIS_TAG.nso"
      - "rtld-armv7-6xx-$TRAVIS_TAG.nso"
    skip-cleanup: true
    tag_name: $TRAVIS_TAG
    on:
      tags: true
condition: $TRAVIS_OS_NAME = linux
